name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Minikube
    steps:
    - name: 1. Check out repository
      uses: actions/checkout@v3

    - name: 2. Start Minikube
      uses: medyagh/setup-minikube@master

    - name: 3. Build image inside Minikube's Docker
      run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devopshint/node-app:latest .
          
    - name: 4. Deploy Application
      run: kubectl apply -f k8s-node-app.yaml

    - name: 5. Verify Deployment Status
      run: |
        echo "--- Waiting for deployment to be ready ---"
        # This command waits up to 2 minutes for the deployment to succeed
        kubectl rollout status deployment/nodejs-app --timeout=120s
        
        echo "--- Pods Status ---"
        kubectl get pods
        
    - name: 6. Test Service and get URL
      run: |
          echo "--- Service List ---"
          minikube service list
          echo "--- Getting Service URL ---"
          minikube service nodejs-app --url
